name: CI

on: [push]
      
jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install contents of Homebrew bundle file
        run: brew bundle check || brew bundle install

