name: Lint

on:
  push:
  pull_request:

jobs:
  brewfile:
    name: Lint Brewfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Lint Brewfile
        run: bash ./bin/lint
